name: Build and Publish to Separate Branch

on:
  push:
    branches:
      - master  # Change this to your main development branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'  # Use the latest LTS version of Node.js

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to dist branch
        if: success()
        run: |
          # Set up Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Save the built file to a temporary location
          mv ./dist/rkgk-huzuni.user.js /tmp/rkgk-huzuni.user.js

          # Switch to the target branch in a clean state
          git checkout --orphan gh-pages

          # Remove all existing files from the branch
          git rm -rf .

          # Move the built file back to the root of the branch
          mv /tmp/rkgk-huzuni.user.js ./rkgk-huzuni.user.js

          # Add, commit, and push the file to the target branch
          git add rkgk-huzuni.user.js
          git commit -m "Build and deploy $(date +'%Y-%m-%d %H:%M:%S')"
          git push -u origin gh-pages --force
